bigbluebutton/bigbluebutton-html-plugin-sdk

- src/core/getPluginApi.ts
- src/data-channel/types.ts
- src/data-channel/useDatachannel.ts
- src/types/common.ts
It fixes the data channel dispatcher function after being bundled.
When bundled, the data channel dispatcher function didn't work as it did in development mode.
Closely related to: https://github.com/bigbluebutton/bigbluebutton/pull/19015
> feat(html5) - fix data channel dispatcher 

- samples/sample-actions-bar-plugin/src/sample-actions-bar-plugin/component.tsx
- src/data-consumption/hooks/index.ts
- src/data-consumption/hooks/useUsersOverview/index.ts
- src/data-consumption/hooks/useUsersOverview/types.ts
- src/data-consumption/hooks/useUsersOverview/useUsersOverview.ts
- src/enums.ts
It adds support for the new hook `useUsersOverview`, though it doesn't include a new plugin sample specially made for it. The sample it is included is the `SampleActionsBarPlugin`, which just logs a message in the console with all the users in it.
Closely related to https://github.com/bigbluebutton/bigbluebutton/pull/19028
> feat(html5) - New Hook useUsersOverview

- samples/sample-data-channel-plugin/src/sample-data-channel-plugin-item/component.tsx
- src/data-channel/hooks.ts
- src/data-channel/types.ts
It basically changes the return type of the hook `useDataChannel` to make it simpler for the plugin developer to fetch data from this hook.
Closes #56
> fix: change return type of useDataChannel

- README.md
- src/core/api/BbbPluginSdk.ts
- src/core/api/types.ts
- src/core/enum.ts
- src/data-consumption/domain/chat/index.ts
- src/data-consumption/domain/chat/loaded-chat-messages/hooks.ts
- src/data-consumption/domain/chat/loaded-chat-messages/types.ts
- src/data-consumption/index.ts
It adds the new data consumption hook: `useLoadedChatMessages`.
Closes #27 
It is closely related to the PR on the core: https://github.com/bigbluebutton/bigbluebutton/pull/19339
> feat(html5): add new useLoadedChatMessages

- README.md
- src/core/api/BbbPluginSdk.ts
- src/core/api/types.ts
- src/data-consumption/domain/user-voice/index.ts
- src/data-consumption/domain/user-voice/talking-indicator/hooks.ts
- src/data-consumption/domain/user-voice/talking-indicator/types.ts
- src/data-consumption/enums.ts
- src/data-consumption/index.ts
- src/ui-commands/commands.ts
- src/ui-commands/external-video/commands.ts
- src/ui-commands/external-video/types.ts
- src/ui-commands/external-video/volume/commands.ts
- src/ui-commands/external-video/volume/enums.ts
- src/ui-commands/external-video/volume/types.ts
- src/ui-commands/types.ts
It creates new hooks for the plugin SDK:
Data Consumption Hook:
- `useTalkingIndicator`;
Ui Command:
- `uiCommands.externalVideo.volume.set`
The first one gives you the information of the user-voice, that being sync with the talking indicator on the meeting and the second gives you the ability to set a specific volume between 0 and 1 of the external video;
Soon there will be an official plugin that decrease the external video when a user is talking, so those two new hooks make it possible
No samples for this one.
Closely related to https://github.com/bigbluebutton/bigbluebutton/pull/19447
> feat(html5): create useTalkingIndicator and set for external video volume

- src/core/api/BbbPluginSdk.ts
- src/core/api/types.ts
- src/data-channel/index.ts
- src/extensible-areas/generic-content-item/component.ts
- src/extensible-areas/generic-content-item/types.ts
- src/index.ts
- src/server-commands/caption/commands.ts
- src/server-commands/caption/enum.ts
- src/server-commands/caption/types.ts
- src/server-commands/commands.ts
- src/server-commands/index.ts
- src/server-commands/types.ts
This PR essentially creates new server-command to send caption via user and also add a new captionLocale.
Other than that, there are a few bugs found in the data-channel flow such as the remove entry function not working, those are already fixed by now.
As mentioned in the title of this PR it is made to support the new typed-captions plugin.
Closely related to https://github.com/bigbluebutton/bigbluebutton/pull/20518
> feat(html5): new server-command for typed-captions plugin

- README.md
- samples/sample-data-channel-plugin/README.md
- samples/sample-data-channel-plugin/src/components/sample-data-channel-plugin-item/component.tsx
- src/data-channel/hooks.ts
- src/data-channel/types.ts
It basically changes the return type from array (just like `React.useState` does) to object (as it is done in the apollo's `useSubscription`).
Closes #89
> feat: Change return type of useDataChannel from array of data to object

- README.md
- samples/sample-user-camera-dropdown-plugin/src/queries.ts
- samples/sample-user-camera-dropdown-plugin/src/sample-user-camera-dropdown-plugin-item/component.tsx
- samples/sample-user-camera-dropdown-plugin/src/sample-user-camera-dropdown-plugin-item/types.ts
- src/core/api/BbbPluginSdk.ts
- src/core/api/types.ts
- src/dom-element-manipulation/enums.ts
- src/dom-element-manipulation/type.ts
- src/dom-element-manipulation/user-camera/hooks.ts
- src/dom-element-manipulation/user-camera/types.ts
- src/extensible-areas/base.ts
- src/extensible-areas/index.ts
- src/extensible-areas/screenshare-helper-item/component.ts
- src/extensible-areas/screenshare-helper-item/enums.ts
- src/extensible-areas/screenshare-helper-item/index.ts
- src/extensible-areas/screenshare-helper-item/types.ts
- src/extensible-areas/user-camera-dropdown-item/component.ts
- src/extensible-areas/user-camera-dropdown-item/types.ts
This PR does 3 related things in general:
- Enhance user-camera-dropdown extensible area;
- Add display function callback to decide in which cameras that dropdown will be shown;
- Add onClick arguments for the dropdown option;  
- Create another extensible-area which is screenshare helper;
- Create another dom-element-manipulation hook: `useUserCameraDomElement`;
See some demo of the 2 first items:
User-camera-dropdown display funcion demo:
https://github.com/user-attachments/assets/53cad8c6-baf2-4768-8ce7-d215a3a3e5cd
Screenshare helper buttons
Closely related to PR in core: https://github.com/bigbluebutton/bigbluebutton/pull/20820
> feat(html5) userCameraDropdown enhancements, user-camera dom-element and screenshareHelper

- README.md
- samples/sample-user-camera-dropdown-plugin/src/sample-user-camera-dropdown-plugin-item/component.tsx
- src/core/api/BbbPluginSdk.ts
- src/core/api/types.ts
- src/core/enum.ts
- src/data-channel/hooks.ts
- src/data-channel/utils.ts
- src/data-consumption/factory/hookCreator.ts
- src/dom-element-manipulation/chat/message/hooks.ts
- src/dom-element-manipulation/chat/message/types.ts
- src/dom-element-manipulation/user-camera/hooks.ts
- src/dom-element-manipulation/user-camera/types.ts
- src/extensible-areas/base.ts
- src/extensible-areas/index.ts
- src/extensible-areas/screenshare-helper-item/component.ts
- src/extensible-areas/screenshare-helper-item/types.ts
- src/extensible-areas/user-camera-helper-item/component.ts
- src/extensible-areas/user-camera-helper-item/enums.ts
- src/extensible-areas/user-camera-helper-item/index.ts
- src/extensible-areas/user-camera-helper-item/types.ts
- Adds new extensible area: userCameraHelper (which is a button added in one of the corners of the user camera);
- Fixes useUserCameraDomElement (the issue was that when a new user enters the room, the dom-element-manipulator hook didn't return the elements);
- Adds a click event to the arguments of the onClick callback function of screenshareHelper;
- Refactors naming of plugin hook events so as to add new event informing bbb-core that the plugin is changing something on its side; 
This PR is closely related to the CORE PR https://github.com/bigbluebutton/bigbluebutton/pull/21004
See a demo of the new userCameraHelper down below:
> fix(html5): fix useUserCameraDomElement behavior and did some refactor

- samples/sample-action-button-dropdown-plugin/src/components/sample-action-button-dropdown-plugin-item/component.tsx
- samples/sample-floating-window-plugin/src/sample-floating-window-plugin-item/component.tsx
- samples/sample-generic-content-sidekick-plugin/src/components/sample-generic-content-sidekick-plugin-item/component.tsx
- src/extensible-areas/floating-window/component.ts
- src/extensible-areas/floating-window/types.ts
- src/extensible-areas/generic-content-item/component.ts
- src/extensible-areas/generic-content-item/types.ts
Changes the return type of `contentFunction` in FloatingWindow and GenericContent extensible areas.
This change is necessary because the components provided by plugins, when rendered in the core, were left in the DOM Tree. This occurs because the plugins and the core are two separate ReactJS applications, each using its own ReactDOM instance. The `contentFunction` must now return the root element created by the plugin's ReactDOM instance to allow the core to properly unmount it.
Closes #112 
Relate Core's PR: 
- https://github.com/bigbluebutton/bigbluebutton/pull/21211
> fix(extensible-areas): change return type of `contentFunction`

- README.md
- src/ui-commands/commands.ts
- src/ui-commands/conference/commands.ts
- src/ui-commands/conference/enums.ts
- src/ui-commands/conference/types.ts
- src/ui-commands/types.ts
- src/ui-commands/user-status/commands.ts
- src/ui-commands/user-status/enums.ts
- src/ui-commands/user-status/types.ts
Adds ui commands to set the user away status and the speaker level(audio output) in the conference.
None
Related BBB-core's PR: 
- https://github.com/bigbluebutton/bigbluebutton/pull/21336
> feat(ui-commands): add user status and conference speaker level

- src/dom-element-manipulation/chat/message/hooks.ts
- src/dom-element-manipulation/chat/message/types.ts
The `useChatMessagesDomElements` hook was designed to expect all DOM elements from the rendered chat messages to be sent in a single event. However, due to the pagination mechanism in the bbb-core, only messages from the same page are sent together, which caused DOM elements from the last rendered page to overwrite those from previous pages.
This PR introduces support for pagination when storing DOM elements, ensuring that elements from different pages do not overwrite each other. It also includes a cleanup mechanism to remove stored DOM elements when a page is unmounted (due to pagination rolling or chat toggling). This ensures that only valid elements are stored and prevents the list from growing indefinitely.
Additionally, the hook's internal state management has been updated and the …
> !fix: track DOM elements in `useChatMessagesDomElements` with pagination

- README.md
- src/core/api/BbbPluginSdk.ts
- src/core/api/types.ts
- src/remote-data/types.ts
- src/remote-data/utils.ts
Implemented `getRemoteData` integration with the new plugin-server architecture.
Make integration with LMS (fetch their data)
To test simply configure the dataResource name in the manifest and then its endpoint in the URL meta parameter that goes in the create request. The manifest would look like:
```json
{
// ...rest of manifest configuration
"remoteDataSources": [
{
"name": "allUsers",
"url": "${meta_pluginSettingsUserInformation}",
"fetchMode": "onMeetingCreate",
"permissions": ["moderator", "viewer"]
}
]
}
```
Then when creating the meeting send the following parameters along, adjusting to your needs and resources:
```
meta_pluginSettingsUserInformation=https://<your-external-source-with-your-authentication>/api/users
pluginsManifests=[{"url": …
```
> feat(plugin-server): Implemented plugin-server integration with SDK.

- src/extensible-areas/action-button-dropdown-item/component.ts
- src/extensible-areas/action-button-dropdown-item/types.ts
- src/extensible-areas/actions-bar-item/component.ts
- src/extensible-areas/actions-bar-item/types.ts
- src/extensible-areas/audio-settings-dropdown-item/component.ts
- src/extensible-areas/audio-settings-dropdown-item/types.ts
- src/extensible-areas/camera-settings-dropdown-item/component.ts
- src/extensible-areas/camera-settings-dropdown-item/types.ts
- src/extensible-areas/floating-window/component.ts
- src/extensible-areas/floating-window/types.ts
- src/extensible-areas/generic-content-item/component.ts
- src/extensible-areas/generic-content-item/types.ts
- src/extensible-areas/nav-bar-item/component.ts
- src/extensible-areas/nav-bar-item/types.ts
- src/extensible-areas/options-dropdown-item/component.ts
- src/extensible-areas/options-dropdown-item/types.ts
- src/extensible-areas/presentation-dropdown-item/component.ts
- src/extensible-areas/presentation-dropdown-item/types.ts
- src/extensible-areas/presentation-toolbar-item/component.ts
- src/extensible-areas/presentation-toolbar-item/types.ts
- src/extensible-areas/screenshare-helper-item/component.ts
- src/extensible-areas/screenshare-helper-item/types.ts
- src/extensible-areas/user-camera-dropdown-item/component.ts
- src/extensible-areas/user-camera-dropdown-item/types.ts
- src/extensible-areas/user-camera-helper-item/component.ts
- src/extensible-areas/user-camera-helper-item/types.ts
- src/extensible-areas/user-list-dropdown-item/component.ts
- src/extensible-areas/user-list-dropdown-item/types.ts
- src/extensible-areas/user-list-item-additional-information/component.ts
- src/extensible-areas/user-list-item-additional-information/types.ts
Add possible way of updating a component without changing it completely, that is setting `id` when constructing the object.
The generic-content-items (mainly sidekick) were unmounting and then mounting again whenever one did update the extensible areas via setter function, and this caused weird behaviours even harming user experience. One interesting case is when the developer wants to build something like this in the plugin:
```ts
useEffect(() => {
pluginApi.setGenericContentItems(
[new GenericContentSidekickArea({
contentFunction: variableContentFunction,
name: variableTitle,
section: 'Section of example',
buttonIcon: 'user',
open: false, // <-- this property is responsible to mount the sidekick menu, but if false, the panel itself will be closed.
// On the other hand, if the property …
```
> feat: Add possible way of updating a component without changing it completely 

- README.md
- samples/sample-action-button-dropdown-plugin/src/components/sample-action-button-dropdown-plugin-item/component.tsx
- src/index.ts
- src/ui-commands/commands.ts
- src/ui-commands/index.ts
- src/ui-commands/notification/commands.ts
- src/ui-commands/notification/enums.ts
- src/ui-commands/notification/types.ts
- src/ui-commands/types.ts
It allows the user to send a notification client-side. If, on the other hand, a developer wants to make it so that everyone receives a notification at the same time,  they can easily do it with the help of a data-channel.
I, myself, used the `sample-action-button-dropdown` to test it. I already left the necessary code change there to make it easier to test. But, one can simply use this API in whatever plugin they want.
See demo, below:
https://github.com/user-attachments/assets/628fbca2-0c5c-416a-86ac-68ce6bc57fdd
We can always change the UI, of course, but mind that this PR doesn't aim to change the structure of the notification itself, it simply wants to simply open the possibility for a plugin to send a notification in the current notify structure.
But again, this is arguable, so if …
> feat(plugins): Notification API support for plugins

- samples/sample-action-button-dropdown-plugin/src/components/sample-action-button-dropdown-plugin-item/component.tsx
- src/ui-commands/actions-bar/commands.ts
- src/ui-commands/actions-bar/enums.ts
- src/ui-commands/actions-bar/types.ts
- src/ui-commands/commands.ts
- src/ui-commands/types.ts
It adds the possibility to display or hide the actions-bar via UI-command.
One can use the SampleActionButtonDropdown in the plugin-SDK to see this feature working, just like in the demo! (See **More** section)
Closely related to https://github.com/bigbluebutton/bigbluebutton/pull/21859
See demo below (just a minor explanation: If the user clicks the button, the plugin sends a ui-command to first close the actions-bar, and then, after 5 seconds, it sends a ui-command again to open it since one can't reach that button again. That's why it  automatically returns, the developer has full control over it).
https://github.com/user-attachments/assets/7cdad3a1-b919-4f30-8e3b-9ad265e0ef85
> feat(plugin): add setDisplayActionsBar ui-command

- samples/sample-use-meeting/manifest.json
Just a quick fix, on the grounds that it had the previous version of the manifest
> fix: fix useMeeting sample manifest

- samples/sample-action-button-dropdown-plugin/manifest.json
- samples/sample-action-button-dropdown-plugin/src/components/sample-action-button-dropdown-plugin-item/component.tsx
- src/asset-persistence/enums.ts
- src/asset-persistence/hook.ts
- src/asset-persistence/types.ts
- src/core/api/BbbPluginSdk.ts
- src/core/api/types.ts
It does 2 things in general:
- Creates a new feature for the plugins to use: the asset-persistence;
- Fix the MaxFileSize error that was not happening;
The second point is there just so I can properly validate if the file size of the presentation that the person is sending is not bigger than expected.
This will allow us to send PDFs into BBB via plugin so that new ways of uploading an h5p file can exist - this is for the h5p-plugin.
Just use the `sample-action-button-dropdown-plugin` in the plugin-sdk repository. It will upload automatically a sample presentation.
To test the expected error, one can decrease the number in `manifest.assetPersistence.maxFileSize` to say 100, which means it allows a file with a maximum of 100 Bytes (pretty much any file you send is greater than that).
See …
> feat(plugin): asset persistence

- README.md
- src/core/api/BbbPluginSdk.ts
- src/core/api/types.ts
- src/core/auxiliary/plugin-information/locale-messages/subscriptions.ts
- src/core/auxiliary/plugin-information/locale-messages/types.ts
- src/core/auxiliary/plugin-information/locale-messages/useLocaleMessages.ts
- src/data-consumption/domain/settings/plugin-settings/utils.ts
This PR adds the hook `useLocaleMessage` to the pluginApi to fetch the locale messages for the internationalization of the plugins. 
Add internationalization for the plugins more easily as requested in the issue https://github.com/bigbluebutton/plugin-typed-captions/issues/6
To test this, there ar 3 PRs that work together here: This one in the CORE, the one in the SDK, mentioned ahead and the one in the typed-captions (which will be sent later on), so the 3 of them must be tested at the same time.
- First, one will have to apply the SDK manually into the plugin-typed-captions (Considering both in the correct branches);
- Run in dev mode;
- So as we are testing it with ngrok, they put some barriers there to avoid security breaches, so to properly make the testing work, do the following:
Go …
> feat(plugins): add useLocaleMessage to plugins

- src/core/api/BbbPluginSdk.ts
- src/core/api/types.ts
- src/core/auxiliary/join-url/getter.ts
This PR changes the `getJoinUrl` function so now it is based on the `bbbWebBase` setting.
One other minor change: Moved this function to be initialized in the `initialize` method and not the getPlugins method. It won't change much in terms of practical behaviour, but it makes the development a lot easier.
Closes #54 
This fix is mostly due to a problem in the `plugin-session-share`. No changes needed there, though.
> fix(getJoinUrl): Fix function to get join URL for cluster setups in BBB

- src/core/api/BbbPluginSdk.ts
- src/core/api/types.ts
- src/core/auxiliary/plugin-unmount/hook.ts
- src/core/auxiliary/plugin-unmount/types.ts
- src/core/enum.ts
- src/core/index.ts
- src/data-consumption/domain/meeting/from-core/hooks.ts
- src/data-consumption/domain/meeting/from-core/types.ts
This PR basically creates a way for the plugin to decide whether to unmount when the meeting is ended or the user is ejected.
This PR fixes the problem where the pick-random-user modal continues open when meeting terminates (if it was open before).
A subsequent PR is going to be sent to the pick-random-user plugin repo implementing this function.
It's worth mentioning that if, for any reason, the plugin dev doesn't want to terminate the plugin once the meeting is over, that's still possible, once this function is not even mandatory. 
Use this branch to test the pick-random-user:
- Open the modal to pick another user;
- End the meeting via API call to bbb-web.
Closely related to CORE PR https://github.com/bigbluebutton/bigbluebutton/pull/22671
Closely related to Plugin PR: …
> feat(plugins): Add support for the plugin to unmount on meeting end

- README.md
This PR adds a comment for Firefox users when testing out their plugin in development mode. Worth mentioning: this doesn't happen in production!
Some developer encountered this problem when using Firefox to test their plugin, this might be a problem that others will face as well.
> doc: Add minor detail to fix development process in firefox

- samples/sample-actions-bar-plugin/src/sample-actions-bar-plugin/component.tsx
- src/extensible-areas/actions-bar-item/component.ts
- src/extensible-areas/actions-bar-item/types.ts
It adds support for a custom svg icon on an actions bar button.
Add more flexibility for the plugin developer to choose an icon for that area. It can be extended for other areas as well in further PRs.
I'd recommend to use the sample plugin `sample-actions-bar-plugin`. Or just add the following snippet to your own plugin:
```ts
new ActionsBarButton({
icon: {
svgContent: (
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="lucide lucide-cctv-icon lucide-cctv">
<path d="M16.75 12h3.632a1 1 0 0 1 .894 1.447l-2.034 4.069a1 1 0 0 1-1.708.134l-2.124-2.97" />
<path d="M17.106 9.053a1 1 0 0 1 .447 1.341l-3.106 6.211a1 1 0 0 1-1.342.447L3.61 12.3a2.92 2.92 0 0 …
```
> feat: add support for custom svg for actions bar buttons

- src/data-consumption/domain/settings/plugin-settings/hooks.ts
- src/data-consumption/domain/settings/plugin-settings/types.ts
- src/data-consumption/domain/settings/plugin-settings/utils.ts
Add support for run plugin tests in BBB's CI. This basically fix the typescript issues that arise from importing a commit and building it all inside the CI. 
Add CI tests for plugins in BBB's repo
Right after the merge of this PR, we need a new version in npmjs. (just a comment)
Closely related to https://github.com/bigbluebutton/bigbluebutton/pull/23028
> ci: Add support for run plugin tests in BBB's CI 

- README.md
It adds a new section to the readme documentation to guide a developer through the development process of the SDK
During the summit week, some developers tried developing new features and got a bit lost in the process, this should help.
See some screenshots of how it will look once merged in:
> doc: Add a guide on how to develop a new feature in the SDK
