- package.json
- tsconfig.production.json
Sets default to cjs publishing on npm
> Prepublish cjs only

- samples/sample-presentation-toolbar-plugin/README.md
- samples/sample-presentation-toolbar-plugin/package.json
- samples/sample-presentation-toolbar-plugin/webpack.config.js
- samples/sample-user-list-dropdown-plugin/README.md
- samples/sample-user-list-dropdown-plugin/package-lock.json
- samples/sample-user-list-dropdown-plugin/package.json
- samples/sample-user-list-dropdown-plugin/webpack.config.js
It basically changes the port that the plugins run when they are on dev mode.
> refactor: change dev port to 4701

- samples/sample-presentation-toolbar-plugin/package-lock.json
- samples/sample-presentation-toolbar-plugin/src/index.css
- samples/sample-presentation-toolbar-plugin/src/index.tsx
- samples/sample-user-list-dropdown-plugin/src/index.css
- samples/sample-user-list-dropdown-plugin/src/index.tsx
It fixes the CSS to not reset the margin nor the padding. This will end up fixing the list generated by the markdown in the chat messages. See video below:
https://github.com/bigbluebutton/bigbluebutton-html-plugin-sdk/assets/69865537/577aaf9f-335a-4cf3-b369-328eae156efb
> fix: CSS misconfigured

- samples/sample-data-channel-plugin/README.md
- samples/sample-data-channel-plugin/package-lock.json
- samples/sample-data-channel-plugin/package.json
- samples/sample-data-channel-plugin/public/index.html
- samples/sample-data-channel-plugin/src/index.tsx
- samples/sample-data-channel-plugin/src/sample-data-channel-plugin-item/component.tsx
- samples/sample-data-channel-plugin/src/sample-data-channel-plugin-item/types.ts
- samples/sample-data-channel-plugin/tsconfig.json
- samples/sample-data-channel-plugin/webpack.config.js
- src/core/getPluginApi.ts
- src/data-channel/index.ts
- src/data-channel/types.ts
- src/data-channel/useDatachannel.ts
- src/enums.ts
- src/index.ts
- src/types/common.ts
It adds support for the new data channels, and adds a sample showing how to play around with it.
Closely related to https://github.com/bigbluebutton/bigbluebutton/pull/19009
> feat(html5): Data channels

- src/core/api/BbbPluginSdk.ts
- src/core/api/types.ts
- src/core/auxiliar/session-token/getter.ts
- src/core/auxiliar/session-token/types.ts
It creates the new `pluginApi.getSessionToken()` that returns the session token from the URL.
closes #49
> feature: pluginApi.getSessionToken()

- README.md
> fix: Change readme

- src/core/api/BbbPluginSdk.ts
- src/data-channel/constants.ts
- src/data-channel/enums.ts
- src/data-channel/hooks.ts
- src/data-channel/index.ts
- src/data-channel/types.ts
- src/data-channel/utils.ts
It implements in the core the delete and reset function
It basically helps the pick random user plugin.
Closely related to https://github.com/bigbluebutton/bigbluebutton/pull/19503
> feat(html5): delete and reset features to data-channel

- src/ui-events/external-video/index.ts
- src/ui-events/external-video/volume/enums.ts
- src/ui-events/external-video/volume/types.ts
- src/ui-events/index.ts
- src/ui-events/types.ts
It basically implements the external video volume changed for the `useUIEvents`.
Closely related to https://github.com/bigbluebutton/plugins/pull/5 and https://github.com/bigbluebutton/bigbluebutton/pull/19615
> feat(html5): implement external-video ui event

- README.md
- samples/sample-action-button-dropdown-plugin/README.md
- samples/sample-actions-bar-plugin/README.md
- samples/sample-audio-settings-dropdown-plugin/README.md
- samples/sample-camera-settings-dropdown-plugin/README.md
- samples/sample-custom-subscription-hook/README.md
- samples/sample-data-channel-plugin/README.md
- samples/sample-dom-element-manipulation/README.md
- samples/sample-floating-window-plugin/README.md
- samples/sample-nav-bar-plugin/README.md
- samples/sample-options-dropdown-plugin/README.md
- samples/sample-presentation-dropdown-plugin/README.md
- samples/sample-presentation-toolbar-plugin/README.md
- samples/sample-ui-commands-plugin/README.md
- samples/sample-ui-events-plugin/README.md
- samples/sample-user-camera-dropdown-plugin/README.md
- samples/sample-user-list-dropdown-plugin/README.md
- samples/sample-user-list-item-additional-information-plugin/README.md
This commit moves some of the duplicated README instruction for each plugin sample to the main README and clarifies some information on how to use the plugins.
> review of the READMEs

- src/index.ts
- src/ui-commands/commands.ts
- src/ui-commands/index.ts
- src/ui-commands/types.ts
> Fix tsc problems

- README.md
- samples/sample-use-meeting/README.md
- samples/sample-use-meeting/package-lock.json
- samples/sample-use-meeting/package.json
- samples/sample-use-meeting/public/index.html
- samples/sample-use-meeting/src/index.tsx
- samples/sample-use-meeting/src/sample-use-meeting/component.tsx
- samples/sample-use-meeting/src/sample-use-meeting/types.ts
- samples/sample-use-meeting/src/utils/logger.ts
- samples/sample-use-meeting/tsconfig.json
- samples/sample-use-meeting/webpack.config.js
- src/core/api/BbbPluginSdk.ts
- src/core/api/types.ts
- src/data-consumption/domain/meeting/from-core/hooks.ts
- src/data-consumption/domain/meeting/from-core/types.ts
- src/data-consumption/domain/meeting/index.ts
- src/data-consumption/enums.ts
- src/data-consumption/index.ts
Create useMeeting from the plugin SDK and add a sample
Closely related to https://github.com/bigbluebutton/bigbluebutton/pull/20097
> feat(html5): Create useMeeting hook for plugin

- src/data-channel/enums.ts
- src/data-channel/hooks.ts
- src/data-channel/types.ts
- src/data-channel/utils.ts
Implement update function for data-channel.
This PR is closely related to https://github.com/bigbluebutton/bigbluebutton/pull/20461 and also will also make itself essential for the h5p-plugin that will soon be out.
> feat(html5): implement update function for data-channel

- .github/ISSUE_TEMPLATE/bigbluebutton-html-plugin-sdk-issue.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
- .github/actions/merge-branches/action.yml
- .github/config.yml
- .github/stale.yml
- .github/workflows/automated-tests-publish-results.yml
- .github/workflows/check-merge-conflict.yml
- .github/workflows/ts-code-compilation.yml
- .github/workflows/ts-code-validation.yml
It adds the `.github` folder for the SDK, and along with that a CI to validate ESlint and TS syntax.
> feat(CI/CD): Add CI for the SDK

- README.md
It fixes some minor issues mentioning the previous plugin architecture. It could confuse the new developers in the project
> fix(documentation): Minor fixes to the readme

- README.md
It adds a complete structure of the manifest to be used as a reference for developers.
> doc: Add complete manifest structure documentation

- README.md
It refactors some parts of the documentation and also adds information and the api for the event persistence in the documentation
> doc: refactor and add event persistence api in the documentation 

- README.md
It adds some more information on the remote-data-source API and also on the meta-parameters.
> doc: Enhance remote-data-source documentation

- README.md
Use npm ci in production build (instead of npm install) in README.md
Closes # none
For a production build we want to replicate exactly the versions of all dependencies as saved in package-lock.json
> docs: use npm ci in production build in README.md

- samples/sample-actions-bar-plugin/src/sample-actions-bar-plugin/component.tsx
Minor fix of an invalid index in actions bar sample.
> fix(samples): invalid option in actions bar

- .gitignore
- README.md
Just updates the readme file to better readability and fix some typos found along the way.
There might be some changes needed after the new security enhancement in the pluginApi.
> docs: Improve docs readability

- README.md
- samples/sample-data-channel-plugin/src/components/sample-data-channel-plugin-item/component.tsx
- src/core/api/BbbPluginSdk.ts
- src/data-channel/enums.ts
- src/ui-data-hooks/layout/index.ts
- src/ui-data-hooks/layout/presentation-area/enums.ts
- src/ui-data-hooks/layout/presentation-area/types.ts
It fixes some typos in the data-channel and in the ui-data-hooks along with some other typos in the readme file.
This adds not only consistency to the code but also will prevent us from having huge failures in the future.
- After the merge of this PR a new version need to be published in npmjs.com
- Closely related PR (from the core): https://github.com/bigbluebutton/bigbluebutton/pull/23155
> fix(data-channel/ui-data-hooks): Fix some typos in the SDK

- README.md
Adds link to the official docs
> docs: add link to official docs
